services:

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    volumes:
      - "${PWD}/frontend/app:/app"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network


  api:
    build: ./backend
    container_name: fastapi
    expose:
      - "8000"
    volumes:
      - "${PWD}/backend:/app"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      .env
    user: "${UID}:${GID}"
    restart: unless-stopped
    networks:
      - app-network

  database:
    image: postgres:15.3
    env_file:
      .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 10s
      retries: 10
      timeout: 5s
    volumes:
      - "${PWD}/database/dumps/movies_dump.sql:/docker-entrypoint-initdb.d/movies_dump.sql"
    restart: unless-stopped
    networks:
      - app-network


  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6300:6300"
    restart: unless-stopped
    networks:
      - app-network


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "3000:8080"
    depends_on:
      - frontend
      - api
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    env_file:
      .env
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network

  jackett:
    build: ./jackett
    container_name: jackett
    env_file:
      - .env
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - "${PWD}/jackett/config:/config/Jackett"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge