services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/frontend/app:/app"
    depends_on:
      - api

  api:
    build: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/backend:/app"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      .env

  database:
    image: postgres:15.3
    env_file:
      .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 3s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6300:6300"
  
  frontend:
    build: ./frontend
    container_name: nodejs
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/frontend:/app"
